var resources_bbdd = [
  {
    titulo: " Docker en Windows 11: Instalación Paso a Paso para Principiantes",
    url: "https://www.youtube.com/watch?v=wMioaU5yk_w",
    tags: ["docker"],
    temas: ["BBDD"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 5,
    idiomas: ["español"],
  },
  {
    titulo: "Curso Docker",
    url: "https://pabpereza.dev/docs/cursos/docker",
    tags: ["docker", "curso"],
    temas: ["BBDD"],
    formatos: ["vídeo", "curso"],
    nivel: ["básico"],
    duracion: 8,
    idiomas: ["español"],
  },
  {
    titulo: "XAMPP Portable desde CERO",
    url: "https://www.youtube.com/playlist?list=PLmHafbyEI2tvBhrm_A5sjnQ6D6KwOJfFW",
    tags: ["XAMPP", "phpMyAdmin"],
    temas: ["BBDD"],
    formatos: ["vídeo", "curso"],
    nivel: ["básico"],
    duracion: 9,
    idiomas: ["español"],
  },
  {
    titulo: "4 - Creación de una Base de Datos con phpMyAdmin",
    url: "https://www.youtube.com/watch?v=mVZUTmoUZ7E&list=PLmHafbyEI2tvBhrm_A5sjnQ6D6KwOJfFW&index=7",
    tags: ["phpMyAdmin", "XAMPP"],
    temas: ["BBDD"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 7,
    idiomas: ["español"],
  },
  {
    titulo: "Exportar una base de datos MySQL desde phpMyAdmin",
    url: "https://www.arsys.es/blog/exportar-base-de-datos-mysql-desde-phpmyadmin?itc=LSOP2E4O-AFTQ4U-QCDI73Z&gclsrc=aw.ds&&acp=23163238293&avl=|||&utm_campaign=SGE-ES-ECO-ECOX-PMX-----Arsys&utm_source=google&utm_medium=cpc&gad_source=1&gad_campaignid=23163281274&gclid=CjwKCAjw1tLOBhAMEiwAiPkRHuhIIxWYk3j0-cPmClECMPbUCPhKlQVSXxhj2KTskGQrjh3ZGO_unRoClwoQAvD_BwE",
    tags: ["phpMyAdmin"],
    temas: ["BBDD"],
    formatos: ["web"],
    nivel: ["básico"],
    duracion: 7,
    idiomas: ["español"],
  },
  {
    titulo: "Docker en Windows - Servidor web XAMP (Apache-MySQL-PHP) utilizando docker",
    url: "https://www.youtube.com/watch?v=Y7jY5Ry3Pok",
    tags: ["phpMyAdmin", "docker", "xampp"],
    temas: ["BBDD"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 7,
    idiomas: ["español"],
  },
];
