var resources_bbdd = [
  {
    titulo: " Docker en Windows 11: Instalación Paso a Paso para Principiantes",
    url: "https://www.youtube.com/watch?v=wMioaU5yk_w",
    tags: ["docker"],
    temas: ["BBDD"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 5,
    idiomas: ["español"],
  },
  {
    titulo: "Curso Docker",
    url: "https://pabpereza.dev/docs/cursos/docker",
    tags: ["docker", "curso"],
    temas: ["BBDD"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 8,
    idiomas: ["español"],
  },
  {
    titulo: "XAMPP Portable desde CERO",
    url: "https://www.youtube.com/playlist?list=PLmHafbyEI2tvBhrm_A5sjnQ6D6KwOJfFW",
    tags: ["XAMPP", "phpMyAdmin"],
    temas: ["BBDD"],
    formatos: ["video", "curso"],
    nivel: ["básico"],
    duracion: 9,
    idiomas: ["español"],
  },
  {
    titulo: "4 - Creación de una Base de Datos con phpMyAdmin",
    url: "https://www.youtube.com/watch?v=mVZUTmoUZ7E&list=PLmHafbyEI2tvBhrm_A5sjnQ6D6KwOJfFW&index=7",
    tags: ["phpMyAdmin", "XAMPP"],
    temas: ["BBDD"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 7,
    idiomas: ["español"],
  },
];
