var resources_trello = [
  {
    titulo: "Trello para Principiantes | Tutorial Completo 2024",
    url: "https://www.youtube.com/watch?v=Fs6DW_dVHuU",
    tags: ["tableros", "listas", "tarjetas"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 12,
    idiomas: ["español"],
  },
  {
    titulo: "¿Qué es Trello y cómo funciona? Guía rápida.",
    url: "https://www.youtube.com/watch?v=tf8ovqLjSkc",
    tags: ["tableros", "intro"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 8,
    idiomas: ["español"],
  },
  {
    titulo: "Cómo organizar un tablero en Trello (Estrategia 2024)",
    url: "https://www.youtube.com/watch?v=5Bu4dLOCkm4",
    tags: ["tableros", "organización"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 9,
    idiomas: ["español"],
  },
  {
    titulo: "Automatizaciones y Power-Ups en Trello (Tutorial).",
    url: "https://www.youtube.com/watch?v=lUYpJs-JzTA",
    tags: ["powerups"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["avanzado"],
    duracion: 14,
    idiomas: ["español"],
  },
  {
    titulo: "Guía de Atajos de Teclado en Trello.",
    url: "https://trello.com/shortcuts",
    tags: ["atajos"],
    practica: ["Trello"],
    formatos: ["web"],
    nivel: ["medio"],
    idiomas: ["español", "inglés"],
  },
  {
    titulo: "Checklists Avanzadas en Trello.",
    url: "https://www.youtube.com/watch?v=8cRzpQU_s0Y",
    tags: ["tarjetas", "checklist"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["medio"],
    duracion: 6,
    idiomas: ["español"],
  },
  {
    titulo: "Trabajo en equipo: Asignar tareas y miembros.",
    url: "https://www.youtube.com/watch?v=rgLzo5QfakY",
    tags: ["colaboracion", "equipo"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 15,
    idiomas: ["español"],
  },
  {
    titulo: "Formato de texto y Markdown en Trello.",
    url: "https://support.atlassian.com/es/trello/docs/how-to-use-markdown-in-trello/",
    tags: ["markdown", "tarjetas"],
    practica: ["Trello"],
    formatos: ["web"],
    nivel: ["medio"],
    idiomas: ["español"],
  },
  {
    titulo: "Gestión de etiquetas y filtros de búsqueda.",
    url: "https://www.youtube.com/shorts/ku2n0mKzkPk",
    tags: ["etiquetas"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["medio"],
    duracion: 1,
    idiomas: ["español"],
  },
  {
    titulo: "Personalizar fondos y portadas de tarjetas.",
    url: "https://blog.trello.com/es/portadas-de-tarjeta-trello",
    tags: ["diseño", "personalizacion"],
    practica: ["Trello"],
    formatos: ["web"],
    nivel: ["básico"],
    idiomas: ["español"],
  },
  {
    titulo: "Campos Personalizados (Custom Fields) en Trello.",
    url: "https://www.youtube.com/watch?v=w44lFiaiAiw",
    tags: ["powerups"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["avanzado"],
    duracion: 5,
    idiomas: ["español"],
  },
  {
    titulo: "Trello App Móvil: Gestión desde el teléfono.",
    url: "https://trello.com/es/mobile",
    tags: ["movil", "app"],
    practica: ["Trello"],
    formatos: ["web"],
    nivel: ["básico"],
    idiomas: ["español"],
  },
  {
    titulo: "Curso intensivo de Trello (Resumen rápido).",
    url: "https://www.youtube.com/watch?v=qKLDImTUihg",
    tags: ["tableros"],
    practica: ["Trello"],
    formatos: ["video"],
    nivel: ["básico"],
    duracion: 14,
    idiomas: ["español"],
  },
];
