var resources_trello = [
  {
    titulo: "Trello para Principiantes | Tutorial Completo 2024",
    url: "https://www.youtube.com/watch?v=Fs6DW_dVHuU",
    tags: ["tableros", "listas", "tarjetas"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 12,
    idiomas: ["español"],
  },
  {
    titulo: "¿Qué es Trello y cómo funciona? Guía rápida.",
    url: "https://www.youtube.com/watch?v=tf8ovqLjSkc",
    tags: ["tableros", "intro"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 8,
    idiomas: ["español"],
  },
  {
    titulo: "Cómo organizar un tablero en Trello (Estrategia 2024)",
    url: "https://www.youtube.com/watch?v=5Bu4dLOCkm4",
    tags: ["tableros", "organización"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 9,
    idiomas: ["español"],
  },
  {
    titulo: "Automatizaciones y Power-Ups en Trello (Tutorial).",
    url: "https://www.youtube.com/watch?v=lUYpJs-JzTA",
    tags: ["powerups"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["avanzado"],
    duracion: 14,
    idiomas: ["español"],
  },
  {
    titulo: "Guía de Atajos de Teclado en Trello.",
    url: "https://trello.com/shortcuts",
    tags: ["atajos"],
    temas: ["Trello"],
    formatos: ["web"],
    nivel: ["medio"],
    idiomas: ["español"],
  },
  {
    titulo: "Checklists Avanzadas en Trello.",
    url: "https://www.youtube.com/watch?v=-jsJxqK-IzE",
    tags: ["tarjetas", "checklist"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["medio"],
    duracion: 6,
    idiomas: ["español"],
  },
  {
    titulo: "Trabajo en equipo: Asignar tareas y miembros.",
    url: "https://www.youtube.com/watch?v=rgLzo5QfakY",
    tags: ["colaboracion", "equipo"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 15,
    idiomas: ["español"],
  },
  {
    titulo: "Curso intensivo de Trello (Resumen rápido).",
    url: "https://www.youtube.com/watch?v=qKLDImTUihg",
    tags: ["tableros"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 14,
    idiomas: ["español"],
  },
  {
    titulo: "Cómo añadir tarjetas y listas en Trello.",
    url: "https://www.youtube.com/watch?v=eb2L2t1WBwc",
    tags: ["tarjetas", "listas"],
    temas: ["Trello"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 14,
    idiomas: ["español"],
  },
];
