var resources_devops = [
  {
    titulo: "Documentación de GitHub Actions (Oficial de GitHub)",
    url: "https://docs.github.com/es/actions",
    tags: ["actions", "github"],
    temas: ["Devops"],
    formatos: ["web"],
    nivel: ["básico"],
    idiomas: ["español"],
  },
  {
    titulo: "Introducción a Github Actions. Sintaxis básica.",
    url: "https://adictosaltrabajo.com/2020/10/28/introduccion-a-github-actions-sintaxis-basica/",
    tags: ["actions"],
    temas: ["Devops"],
    formatos: ["web"],
    nivel: ["básico"],
    idiomas: ["español"],
  },
  {
    titulo: "Curso completo de GitHub Actions en español",
    url: "https://www.youtube.com/playlist?list=PLO9JpmNAsqM7SVT4TgUpzL0ocYLGqiVVQ",
    tags: ["actions"],
    temas: ["Devops"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    idiomas: ["español"],
  },
 {
    titulo: "Github Actions tutorial español - Como usarlas de manera fácil y GRATUITA!",
    url: "https://www.youtube.com/watch?v=wR83hUk45Xs",
    tags: ["actions"],
    temas: ["Devops"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    duracion: 14,
    idiomas: ["español"],
  },
  {
    titulo: "Complete GitHub Actions Course - From BEGINNER to PRO",
    url: "https://www.youtube.com/watch?v=Xwpi0ITkL3U",
    tags: ["actions"],
    temas: ["Devops"],
    formatos: ["vídeo"],
    nivel: ["básico"],
    idiomas: ["inglés"],
  },  
];
